# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Stormwater Solutions LLC
title_separator          : "-"
subtitle                 : # Home to the New River Valley's First and Foremost Stormwater Solution Corporation
name                     : Stormwater Solutions
description              : Website for Stormwater Solutions LLC. Operating out of the New River Valley since 2016
baseurl                  : "/StormwaterSolutionsLLC" # Set this to your repo name for GitHub Pages
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
